In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('titanic.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
mean_age=int(df['Age'].mean().round())
df['Age']=df['Age'].fillna(mean_age)

df['Embarked']=df['Embarked'].fillna(method='ffill')

df=df.drop('Cabin',axis=1)

/tmp/ipython-input-96-2761424189.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Embarked']=df['Embarked'].fillna(method='ffill')

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,30.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [ ]:
original_df=df.copy()

In [ ]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder

In [ ]:
le=LabelEncoder()
df['Embarked']=le.fit_transform(df['Embarked'])
df['Sex']=le.fit_transform(df['Sex'])

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,0
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,2
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,2
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",1,27.0,0,0,211536,13.0000,2
887,888,1,1,"Graham, Miss. Margaret Edith",0,19.0,0,0,112053,30.0000,2
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",0,30.0,1,2,W./C. 6607,23.4500,2
889,890,1,1,"Behr, Mr. Karl Howell",1,26.0,0,0,111369,30.0000,0
890,891,0,3,"Dooley, Mr. Patrick",1,32.0,0,0,370376,7.7500,1

In [ ]:
df=original_df

In [ ]:
ohe = OneHotEncoder()

In [ ]:
sex_ohe =ohe.fit_transform(df[['Sex']]).toarray()
sex_ohe

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [ ]:
sex_ohe_df =pd.DataFrame(sex_ohe,columns=ohe.get_feature_names_out())
sex_ohe_df

     Sex_female  Sex_male
0           0.0       1.0
1           1.0       0.0
2           1.0       0.0
3           1.0       0.0
4           0.0       1.0
..          ...       ...
886         0.0       1.0
887         1.0       0.0
888         1.0       0.0
889         0.0       1.0
890         0.0       1.0

[891 rows x 2 columns]

In [ ]:
df=pd.concat([df,sex_ohe_df],axis=1)

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Sex_female,Sex_male
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0.0,1.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1.0,0.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,1.0,0.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1.0,0.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,0.0,1.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,1.0,0.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,30.0,1,2,W./C. 6607,23.4500,S,1.0,0.0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,0.0,1.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,0.0,1.0

In [ ]:
df=original_df

In [ ]:
oe1 = OrdinalEncoder(categories=[['Q','S','C']])
em_oe=oe1.fit_transform(df[['Embarked']])
em_oe_df=pd.DataFrame(em_oe,columns=['Embarked_Encoded'])
df=pd.concat([df,em_oe_df],axis=1)
df=df.drop('Embarked',axis=1)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_Encoded
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,1.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,2.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,1.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,1.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,1.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,1.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,1.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,30.0,1,2,W./C. 6607,23.4500,1.0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,2.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,0.0

In [ ]:
oe2 = OrdinalEncoder(categories=[['male','female']])
sex_oe=oe2.fit_transform(df[['Sex']])
sex_oe_df=pd.DataFrame(sex_oe,columns=['Sex_Encoded'])
df=pd.concat([df,sex_oe_df],axis=1)
df=df.drop('Sex',axis=1)
df

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Embarked_Encoded,Sex_Encoded
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,1.0,0.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,2.0,1.0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,1.0,1.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,1.0,1.0
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,1.0,0.0
887,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,1.0,1.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",30.0,1,2,W./C. 6607,23.4500,1.0,1.0
889,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,2.0,0.0
890,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,0.0,0.0

In [ ]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [ ]:
new_df=df.drop(['Name','Ticket'],axis=1)
new_df

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked_Encoded,Sex_Encoded
0,1,0,3,22.0,1,0,7.2500,1.0,0.0
1,2,1,1,38.0,1,0,71.2833,2.0,1.0
2,3,1,3,26.0,0,0,7.9250,1.0,1.0
3,4,1,1,35.0,1,0,53.1000,1.0,1.0
4,5,0,3,35.0,0,0,8.0500,1.0,0.0
...,...,...,...,...,...,...,...,...,...
886,887,0,2,27.0,0,0,13.0000,1.0,0.0
887,888,1,1,19.0,0,0,30.0000,1.0,1.0
888,889,0,3,30.0,1,2,23.4500,1.0,1.0
889,890,1,1,26.0,0,0,30.0000,2.0,0.0
890,891,0,3,32.0,0,0,7.7500,0.0,0.0

In [ ]:
ss=StandardScaler()

In [ ]:
ss_scaled_data=ss.fit_transform(new_df)
ss_scaled_data

array([[-1.73010796, -0.78927234,  0.82737724, ..., -0.50244517,
        -0.19773453, -0.73769513],
       [-1.72622007,  1.2669898 , -1.56610693, ...,  0.78684529,
         1.73832554,  1.35557354],
       [-1.72233219,  1.2669898 ,  0.82737724, ..., -0.48885426,
        -0.19773453,  1.35557354],
       ...,
       [ 1.72233219, -0.78927234,  0.82737724, ..., -0.17626324,
        -0.19773453,  1.35557354],
       [ 1.72622007,  1.2669898 , -1.56610693, ..., -0.04438104,
         1.73832554, -0.73769513],
       [ 1.73010796, -0.78927234,  0.82737724, ..., -0.49237783,
        -2.1337946 , -0.73769513]])

In [ ]:
ss_scaled_df = pd.DataFrame(ss_scaled_data, columns=new_df.columns)
ss_scaled_df

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked_Encoded,Sex_Encoded
0,-1.730108,-0.789272,0.827377,-0.597055,0.432793,-0.473674,-0.502445,-0.197735,-0.737695
1,-1.726220,1.266990,-1.566107,0.634162,0.432793,-0.473674,0.786845,1.738326,1.355574
2,-1.722332,1.266990,0.827377,-0.289251,-0.474545,-0.473674,-0.488854,-0.197735,1.355574
3,-1.718444,1.266990,-1.566107,0.403309,0.432793,-0.473674,0.420730,-0.197735,1.355574
4,-1.714556,-0.789272,0.827377,0.403309,-0.474545,-0.473674,-0.486337,-0.197735,-0.737695
...,...,...,...,...,...,...,...,...,...
886,1.714556,-0.789272,-0.369365,-0.212299,-0.474545,-0.473674,-0.386671,-0.197735,-0.737695
887,1.718444,1.266990,-1.566107,-0.827908,-0.474545,-0.473674,-0.044381,-0.197735,1.355574
888,1.722332,-0.789272,0.827377,0.018554,0.432793,2.008933,-0.176263,-0.197735,1.355574
889,1.726220,1.266990,-1.566107,-0.289251,-0.474545,-0.473674,-0.044381,1.738326,-0.737695
890,1.730108,-0.789272,0.827377,0.172456,-0.474545,-0.473674,-0.492378,-2.133795,-0.737695

In [ ]:
mms=MinMaxScaler()

In [ ]:
mms_scaled_data=mms.fit_transform(new_df)
mms_scaled_data

array([[0.        , 0.        , 1.        , ..., 0.01415106, 0.5       ,
        0.        ],
       [0.0011236 , 1.        , 0.        , ..., 0.13913574, 1.        ,
        1.        ],
       [0.00224719, 1.        , 1.        , ..., 0.01546857, 0.5       ,
        1.        ],
       ...,
       [0.99775281, 0.        , 1.        , ..., 0.04577135, 0.5       ,
        1.        ],
       [0.9988764 , 1.        , 0.        , ..., 0.0585561 , 1.        ,
        0.        ],
       [1.        , 0.        , 1.        , ..., 0.01512699, 0.        ,
        0.        ]])

In [ ]:
mms_scaled_df = pd.DataFrame(mms_scaled_data, columns=new_df.columns)
mms_scaled_df

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Embarked_Encoded,Sex_Encoded
0,0.000000,0.0,1.0,0.271174,0.125,0.000000,0.014151,0.5,0.0
1,0.001124,1.0,0.0,0.472229,0.125,0.000000,0.139136,1.0,1.0
2,0.002247,1.0,1.0,0.321438,0.000,0.000000,0.015469,0.5,1.0
3,0.003371,1.0,0.0,0.434531,0.125,0.000000,0.103644,0.5,1.0
4,0.004494,0.0,1.0,0.434531,0.000,0.000000,0.015713,0.5,0.0
...,...,...,...,...,...,...,...,...,...
886,0.995506,0.0,0.5,0.334004,0.000,0.000000,0.025374,0.5,0.0
887,0.996629,1.0,0.0,0.233476,0.000,0.000000,0.058556,0.5,1.0
888,0.997753,0.0,1.0,0.371701,0.125,0.333333,0.045771,0.5,1.0
889,0.998876,1.0,0.0,0.321438,0.000,0.000000,0.058556,1.0,0.0
890,1.000000,0.0,1.0,0.396833,0.000,0.000000,0.015127,0.0,0.0

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Embarked_Encoded,Sex_Encoded
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,1.0,0.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,2.0,1.0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,1.0,1.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,1.0,1.0
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,1.0,0.0
887,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,1.0,1.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",30.0,1,2,W./C. 6607,23.4500,1.0,1.0
889,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,2.0,0.0
890,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,0.0,0.0

In [ ]:
bins=[0,12,19,30,50,max(df['Age'])]
labels=['child','teenagers','audlt','middle-aged Adults','seniors']
df['Age']=pd.cut(df['Age'],bins=bins,labels=labels)
df

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Embarked_Encoded,Sex_Encoded
0,1,0,3,"Braund, Mr. Owen Harris",audlt,1,0,A/5 21171,7.2500,1.0,0.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",middle-aged Adults,1,0,PC 17599,71.2833,2.0,1.0
2,3,1,3,"Heikkinen, Miss. Laina",audlt,0,0,STON/O2. 3101282,7.9250,1.0,1.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",middle-aged Adults,1,0,113803,53.1000,1.0,1.0
4,5,0,3,"Allen, Mr. William Henry",middle-aged Adults,0,0,373450,8.0500,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",audlt,0,0,211536,13.0000,1.0,0.0
887,888,1,1,"Graham, Miss. Margaret Edith",teenagers,0,0,112053,30.0000,1.0,1.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",audlt,1,2,W./C. 6607,23.4500,1.0,1.0
889,890,1,1,"Behr, Mr. Karl Howell",audlt,0,0,111369,30.0000,2.0,0.0
890,891,0,3,"Dooley, Mr. Patrick",middle-aged Adults,0,0,370376,7.7500,0.0,0.0

In [ ]:
cost_label=['low cost','medium-low cost','medium-high cost','very-high cost']
df['Fare']=pd.qcut(df['Fare'],q=4,labels=cost_label)
df

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Embarked_Encoded,Sex_Encoded
0,1,0,3,"Braund, Mr. Owen Harris",audlt,1,0,A/5 21171,low cost,1.0,0.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",middle-aged Adults,1,0,PC 17599,very-high cost,2.0,1.0
2,3,1,3,"Heikkinen, Miss. Laina",audlt,0,0,STON/O2. 3101282,medium-low cost,1.0,1.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",middle-aged Adults,1,0,113803,very-high cost,1.0,1.0
4,5,0,3,"Allen, Mr. William Henry",middle-aged Adults,0,0,373450,medium-low cost,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",audlt,0,0,211536,medium-low cost,1.0,0.0
887,888,1,1,"Graham, Miss. Margaret Edith",teenagers,0,0,112053,medium-high cost,1.0,1.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",audlt,1,2,W./C. 6607,medium-high cost,1.0,1.0
889,890,1,1,"Behr, Mr. Karl Howell",audlt,0,0,111369,medium-high cost,2.0,0.0
890,891,0,3,"Dooley, Mr. Patrick",middle-aged Adults,0,0,370376,low cost,0.0,0.0